### ISSUE TITLE
Create Stream Component

### ISSUE THREAD

**Issue by hminsky2002** [hminsky2002/WNYU#9]
Now that www.wnyu-ice-cast-relay.com is live with the Rocket Streaming Audio Server setup as an icecast relay, we have a stream that is both ssl certified and receiving metadata from spinitron. This would be a good first component to render. Furthermore, Rocket seems to provide a web component interface that will [translate a metadata push into a browser event](https://rocketbroadcaster.com/streaming-audio-server/docs/players.html), so repeatedly calling may not be an issue.

**Comment by jmatraszek** [comment]
Hey, just wanted to say thanks — I was looking for HTTPS stream of WNYU (to play it in navidrome) and found it here. :)
